{% set name = "CountEst" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CountEst-{{ version }}.tar.gz
  sha256: cad713aff680ea95c4f6a1d5466f35baa2a1f2d8786604c39e22a7f9758af83e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.5
    - pandas >=1.1.5
    - scikit-learn

test:
  imports:
    - CountEst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanskriti-02/CountEst
  summary: CountEst is a module containing the implementation of count-based estimators, i.e., supervised learning algorithms that make predictions based on the frequency or count of specific events, categories, or values within a dataset.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/sanskriti-02/CountEst

extra:
  recipe-maintainers:
    - sanskriti-02
